### ISSUE TITLE
Please provide the pre-trained checkpoints

### ISSUE THREAD

**Issue by guyleaf** [facebookresearch/generalized-schrodinger-bridge-matching#1]
Hi
I try to reproduce the results of AFHQ.
It seems the checkpoint `vae.ckpt` is missing.

Could you provide the instruction how to download it?

Thanks.

**Comment by ghliu** [comment]
Hi @guyleaf ! The checkpoints to pretrained VAE and the diffusion model for AFHQ experiments can be found in [this jupyter notebook](https://github.com/facebookresearch/generalized-schrodinger-bridge-matching/blob/main/notebooks/afhq_sample.ipynb). Hope this helps!
